# Generated by Django 5.0.9 on 2026-07-10 08:58

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0187_alter_device_vc_position'),
        ('extras', '0116_custom_link_button_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rack_layout', to='dcim.location')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Layout',
                'verbose_name_plural': 'Layouts',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='LayoutObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('rotation', models.FloatField(default=0)),
                ('z_index', models.IntegerField(default=0)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='netbox_rack_layout.layout')),
            ],
            options={
                'verbose_name': 'Layout Object',
                'verbose_name_plural': 'Layout Objects',
                'ordering': ['z_index'],
                'unique_together': {('layout', 'object_type', 'object_id')},
            },
        ),
    ]
