# Generated by Django 5.0.9 on 2026-07-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rack_layout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutobject',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_objects', to='netbox_rack_layout.layout'),
        ),
    ]
