# Generated by Django 5.0.9 on 2026-07-15 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0187_alter_device_vc_position'),
        ('netbox_rack_layout', '0003_layoutobject_width_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_layout', to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_layout', to='dcim.location'),
        ),
    ]
