# Generated by Django 5.0.9 on 2026-07-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rack_layout', '0004_layout_site_alter_layout_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutobject',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layoutobject',
            name='parent_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
