# Generated by Django 5.0.9 on 2026-09-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rack_layout', '0005_layoutobject_parent_id_layoutobject_parent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutobject',
            name='wall_face',
            field=models.CharField(
                blank=True,
                choices=[('front', 'Mặt trước'), ('back', 'Mặt sau')],
                default='front',
                max_length=10,
                null=True,
            ),
        ),
    ]
