# Generated by Django 5.0.9 on 2026-09-21 22:06

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0187_alter_device_vc_position'),
        ('extras', '0116_custom_link_button_color'),
        ('netbox_rack_layout', '0006_layoutobject_wall_face'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTemperatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('min_temp', models.FloatField(default=20.0)),
                ('max_temp', models.FloatField(default=30.0)),
                ('interval_seconds', models.PositiveIntegerField(default=5)),
                ('is_auto_simulate', models.BooleanField(default=False)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_config', to='dcim.location')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Cấu hình nhiệt độ Location',
                'verbose_name_plural': 'Cấu hình nhiệt độ Locations',
            },
        ),
        migrations.CreateModel(
            name='TemperatureState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('current_temp', models.FloatField(default=25.0)),
                ('status', models.CharField(default='normal', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_states', to='dcim.location')),
            ],
            options={
                'verbose_name': 'Trạng thái nhiệt độ',
                'verbose_name_plural': 'Trạng thái nhiệt độ',
                'unique_together': {('location', 'object_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='TemperatureTimeSeriesLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('object_type', models.CharField(db_index=True, max_length=20)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('object_name', models.CharField(blank=True, max_length=150)),
                ('temperature', models.FloatField()),
                ('status', models.CharField(default='normal', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_logs', to='dcim.location')),
            ],
            options={
                'verbose_name': 'Log nhiệt độ Time-Series',
                'verbose_name_plural': 'Logs nhiệt độ Time-Series',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['location', '-timestamp'], name='netbox_rack_locatio_587ec3_idx'), models.Index(fields=['location', 'object_type', 'object_id', '-timestamp'], name='netbox_rack_locatio_de7f1e_idx')],
            },
        ),
    ]
