# Generated by Django 5.0.9 on 2026-09-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rack_layout', '0007_locationtemperatureconfig_temperaturestate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturestate',
            name='max_temp',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='temperaturestate',
            name='min_temp',
            field=models.FloatField(default=20.0),
        ),
    ]
