# Generated by Django 5.0.9 on 2026-08-05 08:36

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0187_alter_device_vc_position'),
        ('extras', '0116_custom_link_button_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixHostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('host_name', models.CharField(max_length=255)),
                ('visible_name', models.CharField(blank=True, default='', max_length=255)),
                ('use_device_role_as_group', models.BooleanField(default=True)),
                ('custom_groups', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('proxy_hostid', models.CharField(blank=True, default='', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('templates', models.JSONField(blank=True, default=list)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zabbix_config', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Cấu hình Zabbix Host',
                'verbose_name_plural': 'Cấu hình Zabbix Hosts',
                'ordering': ('host_name',),
            },
        ),
        migrations.CreateModel(
            name='ZabbixInterfaceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('interface_type', models.CharField(default='1', max_length=10)),
                ('ip_address', models.CharField(blank=True, default='', max_length=255)),
                ('dns_name', models.CharField(blank=True, default='', max_length=255)),
                ('use_ip', models.BooleanField(default=True)),
                ('port', models.CharField(default='10050', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('host_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='netbox_zabbix_plugin.zabbixhostconfig')),
            ],
            options={
                'verbose_name': 'Giao diện Zabbix Interface',
                'verbose_name_plural': 'Giao diện Zabbix Interfaces',
            },
        ),
    ]
