# Generated by Django 5.0.9 on 2026-07-06 08:42

import django.core.validators
import django.db.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0187_alter_device_vc_position'),
        ('extras', '0116_custom_link_button_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('expected_date', models.DateField()),
                ('reason', models.TextField(max_length=500)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('admin_reason', models.TextField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.region')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Phiếu yêu cầu ra vào',
                'verbose_name_plural': 'Phiếu yêu cầu ra vào',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='netbox_access_request.accessrequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử yêu cầu',
                'verbose_name_plural': 'Lịch sử yêu cầu',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RequestSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('id_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Mã định danh phải có đúng 12 ký tự số', regex='^\\d{12}$')])),
                ('full_name', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có 10 chữ số và bắt đầu bằng 0', regex='^0\\d{9}$')])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('verify_status', models.CharField(default='pending', max_length=30)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='netbox_access_request.accessrequest')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.location')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Đối tượng',
                'verbose_name_plural': 'Đối tượng',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='UserRegionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='dcim.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phân quyền Region',
                'verbose_name_plural': 'Phân quyền Region',
                'unique_together': {('user', 'region')},
            },
        ),
    ]
