# Generated by Django 5.0.9 on 2026-07-12 14:22

import django.core.validators
import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0187_alter_device_vc_position'),
        ('extras', '0116_custom_link_button_color'),
        ('netbox_asset_management', '0003_asset_tags_assetgroup_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('device_type', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_period', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('warranty_end', models.DateField(blank=True, editable=False, null=True)),
                ('rack_face', models.CharField(blank=True, max_length=30)),
                ('asset_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_locks', to='netbox_asset_management.assetgroup')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.location')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.rack')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.region')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Smart Lock',
                'verbose_name_plural': 'Smart Locks',
                'ordering': ('-last_updated', 'name'),
            },
        ),
    ]
